mod ai_chunk_merge_node;
mod ai_chunk_node;
mod ai_chunk_semantic_node;
pub(crate) mod ai_embed_node;
mod arangodb_node;
mod cache_node;
pub(crate) mod code_node;
mod conditional_node;
mod db_node;
mod delay_node;
mod extract_node;
mod file_node;
mod foreach_node;
mod hash_node;
mod http_node;
mod llm_node;
mod log_node;
mod lua_sandbox;
mod markdown_node;
mod pdf_image_node;
mod s3_node;
mod shell_node;
pub(crate) mod subworkflow_node;
mod template_node;
mod transform_node;
mod validate_node;

use crate::nodes::NodeRegistry;
use std::sync::Arc;

/// Register all built-in nodes into the registry.
pub fn register_all(registry: &mut NodeRegistry) {
    registry.register(Arc::new(log_node::LogNode));
    registry.register(Arc::new(delay_node::DelayNode));
    registry.register(Arc::new(shell_node::ShellCommandNode));
    registry.register(Arc::new(http_node::HttpRequestNode));
    registry.register(Arc::new(http_node::HttpGetNode));
    registry.register(Arc::new(http_node::HttpPostNode));
    registry.register(Arc::new(http_node::HttpPutNode));
    registry.register(Arc::new(http_node::HttpDeleteNode));
    registry.register(Arc::new(file_node::ReadFileNode));
    registry.register(Arc::new(file_node::WriteFileNode));
    registry.register(Arc::new(file_node::CopyFileNode));
    registry.register(Arc::new(file_node::MoveFileNode));
    registry.register(Arc::new(file_node::DeleteFileNode));
    registry.register(Arc::new(file_node::ListDirectoryNode));
    registry.register(Arc::new(transform_node::JsonParseNode));
    registry.register(Arc::new(transform_node::JsonStringifyNode));
    registry.register(Arc::new(transform_node::JsonExtractPathNode));
    registry.register(Arc::new(transform_node::CsvParseNode));
    registry.register(Arc::new(transform_node::CsvStringifyNode));
    registry.register(Arc::new(transform_node::SelectFieldsNode));
    registry.register(Arc::new(transform_node::RenameFieldsNode));
    registry.register(Arc::new(transform_node::DataFilterNode));
    registry.register(Arc::new(transform_node::DataTransformNode));
    registry.register(Arc::new(transform_node::BatchNode));
    registry.register(Arc::new(transform_node::DeduplicateNode));
    registry.register(Arc::new(conditional_node::IfNode));
    registry.register(Arc::new(conditional_node::SwitchNode));
    registry.register(Arc::new(conditional_node::IfHttpStatusNode));
    registry.register(Arc::new(conditional_node::IfBodyContainsNode));
    registry.register(Arc::new(validate_node::ValidateSchemaNode));
    registry.register(Arc::new(validate_node::JsonValidateNode));
    registry.register(Arc::new(template_node::TemplateRenderNode));
    registry.register(Arc::new(hash_node::HashNode));
    registry.register(Arc::new(code_node::CodeNode));
    registry.register(Arc::new(markdown_node::MarkdownToHtmlNode));
    registry.register(Arc::new(markdown_node::HtmlToMarkdownNode));
    registry.register(Arc::new(extract_node::ExtractWordNode));
    registry.register(Arc::new(extract_node::ExtractPdfNode));
    registry.register(Arc::new(extract_node::ExtractHtmlNode));
    registry.register(Arc::new(extract_node::ExtractVttNode));
    registry.register(Arc::new(extract_node::ExtractSrtNode));
    registry.register(Arc::new(foreach_node::ForEachNode));
    registry.register(Arc::new(s3_node::S3PresignUrlNode));
    registry.register(Arc::new(s3_node::S3GetObjectNode));
    registry.register(Arc::new(s3_node::S3PutObjectNode));
    registry.register(Arc::new(s3_node::S3DeleteObjectNode));
    registry.register(Arc::new(s3_node::S3CopyObjectNode));
    registry.register(Arc::new(s3_node::S3ListObjectsNode));
    registry.register(Arc::new(s3_node::S3ListBucketsNode));
    registry.register(Arc::new(cache_node::CacheSetNode));
    registry.register(Arc::new(cache_node::CacheGetNode));
    registry.register(Arc::new(db_node::DbQueryNode));
    registry.register(Arc::new(db_node::DbExecNode));
    registry.register(Arc::new(arangodb_node::ArangoDbAqlNode));

    registry.register(Arc::new(ai_chunk_node::AiChunkNode));
    registry.register(Arc::new(ai_chunk_merge_node::AiChunkMergeNode));
    registry.register(Arc::new(ai_chunk_semantic_node::AiChunkSemanticNode));
    registry.register(Arc::new(ai_embed_node::AiEmbedNode));
    registry.register(Arc::new(llm_node::LlmNode));

    registry.register(Arc::new(pdf_image_node::PdfToImageNode));
    registry.register(Arc::new(pdf_image_node::PdfThumbnailNode));
    registry.register(Arc::new(pdf_image_node::ImageToPdfNode));
    registry.register(Arc::new(pdf_image_node::PdfMetadataNode));
    registry.register(Arc::new(pdf_image_node::ImageResizeNode));
    registry.register(Arc::new(pdf_image_node::ImageCropNode));
    registry.register(Arc::new(pdf_image_node::ImageRotateNode));
    registry.register(Arc::new(pdf_image_node::ImageFlipNode));
    registry.register(Arc::new(pdf_image_node::ImageGrayscaleNode));
}
